/* eslint-disable */
export default {
  "key": "common",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "appName": "Marketplace Mandi",
        "welcome": "Welcome",
        "loading": "Loading...",
        "search": "Search",
        "searchProducts": "Search products...",
        "welcomeToMandi": "Welcome to Mandi",
        "indianAgriculture": "Indian Agriculture",
        "mandiPlatform": "Mandi Platform",
        "platformDescription": "AI-powered multilingual marketplace connecting farmers and traders. Trade in 22 Indian languages.",
        "login": "Login",
        "profile": "Profile",
        "createListing": "Create Listing",
        "aiInsights": "AI Insights",
        "home": "Home",
        "listings": "Listings",
        "dashboard": "Dashboard",
        "settings": "Settings",
        "register": "Register",
        "logout": "Logout",
        "success": "Success",
        "error": "Error",
        "selectLanguage": "Select Language"
      },
      "hi": {
        "appName": "मार्केटप्लेस मंडी",
        "welcome": "स्वागत",
        "loading": "लोड हो रहा है...",
        "search": "खोजें",
        "searchProducts": "उत्पाद खोजें...",
        "welcomeToMandi": "मंडी में स्वागत है",
        "indianAgriculture": "भारतीय कृषि",
        "mandiPlatform": "मंडी प्लेटफॉर्म",
        "platformDescription": "किसानों और व्यापारियों को जोड़ने वाला AI-संचालित बहुभाषी मार्केटप्लेस। 22 भारतीय भाषाओं में व्यापार करें।",
        "login": "लॉग इन",
        "profile": "प्रोफाइल",
        "createListing": "लिस्टिंग बनाएं",
        "aiInsights": "AI अंतर्दृष्टि",
        "home": "होम",
        "listings": "लिस्टिंग",
        "dashboard": "डैशबोर्ड",
        "settings": "सेटिंग्स",
        "register": "रजिस्टर करें",
        "logout": "लॉग आउट",
        "success": "सफलता",
        "error": "त्रुटि",
        "selectLanguage": "भाषा चुनें"
      },
      "bn": {
        "appName": "মার্কেটপ্লেস মান্ডি",
        "welcome": "স্বাগতম",
        "loading": "লোড হচ্ছে...",
        "search": "অনুসন্ধান",
        "searchProducts": "পণ্য খুঁজুন...",
        "welcomeToMandi": "মান্ডিতে স্বাগতম",
        "indianAgriculture": "ভারতীয় কৃষি",
        "mandiPlatform": "মান্ডি প্ল্যাটফর্ম",
        "platformDescription": "কৃষক এবং ব্যবসায়ীদের সংযোগকারী AI-চালিত বহুভাষিক মার্কেটপ্লেস। ২২টি ভারতীয় ভাষায় ব্যবসা করুন।",
        "login": "লগ ইন",
        "profile": "প্রোফাইল",
        "createListing": "লিস্টিং তৈরি করুন",
        "aiInsights": "AI অন্তর্দৃষ্টি",
        "home": "হোম",
        "listings": "তালিকা",
        "dashboard": "ড্যাশবোর্ড",
        "settings": "সেটিংস",
        "register": "নিবন্ধন",
        "logout": "লগ আউট",
        "success": "সফলতা",
        "error": "ত্রুটি",
        "selectLanguage": "ভাষা নির্বাচন করুন"
      },
      "ta": {
        "appName": "மார்க்கெட்பிளேஸ் மண்டி",
        "welcome": "வரவேற்கிறோம்",
        "loading": "ஏற்றுகிறது...",
        "search": "தேடு",
        "searchProducts": "பொருட்களைத் தேடுங்கள்...",
        "welcomeToMandi": "மண்டிக்கு வரவேற்கிறோம்",
        "indianAgriculture": "இந்திய விவசாயம்",
        "mandiPlatform": "மண்டி தளம்",
        "platformDescription": "விவசாயிகள் மற்றும் வணிகர்களை இணைக்கும் AI-இயங்கும் பன்மொழி சந்தை। 22 இந்திய மொழிகளில் வணிகம் செய்யுங்கள்।",
        "login": "உள்நுழை",
        "profile": "சுயவிவரம்",
        "createListing": "பட்டியல் உருவாக்கவும்",
        "aiInsights": "AI நுண்ணறிவு",
        "home": "முகப்பு",
        "listings": "பட்டியல்கள்",
        "dashboard": "டாஷ்போர்டு",
        "settings": "அமைப்புகள்",
        "register": "பதிவு செய்யுங்கள்",
        "logout": "வெளியேறு",
        "success": "வெற்றி",
        "error": "பிழை",
        "selectLanguage": "மொழியைத் தேர்ந்தெடுக்கவும்"
      },
      "te": {
        "appName": "మార్కెట్‌ప్లేస్ మండి",
        "welcome": "స్వాగతం",
        "loading": "లోడ్ అవుతోంది...",
        "search": "వెతకండి",
        "searchProducts": "ఉత్పత్తులను వెతకండి...",
        "welcomeToMandi": "మండికి స్వాగతం",
        "indianAgriculture": "భారతీయ వ్యవసాయం",
        "mandiPlatform": "మండి ప్లాట్‌ఫారమ్",
        "platformDescription": "రైతులు మరియు వ్యాపారులను కలిపే AI-ఆధారిత బహుభాషా మార్కెట్‌ప్లేస్। 22 భారతీయ భాషలలో వ్యాపారం చేయండి।",
        "login": "లాగిన్",
        "profile": "ప్రొఫైల్",
        "createListing": "లిస్టింగ్ సృష్టించండి",
        "aiInsights": "AI అంతర్దృష్టులు",
        "home": "హోమ్",
        "listings": "జాబితాలు",
        "dashboard": "డాష్‌బోర్డ్",
        "settings": "సెట్టింగులు",
        "register": "నమోదు చేయండి",
        "logout": "లాగ్ అవుట్",
        "success": "విజయం",
        "error": "లోపం",
        "selectLanguage": "భాషను ఎంచుకోండి"
      },
      "gu": {
        "appName": "માર્કેટપ્લેસ મંડી",
        "welcome": "સ્વાગત છે",
        "loading": "લોડ થઈ રહ્યું છે...",
        "search": "શોધો",
        "searchProducts": "ઉત્પાદનો શોધો...",
        "welcomeToMandi": "મંડીમાં સ્વાગત છે",
        "indianAgriculture": "ભારતીય કૃષિ",
        "mandiPlatform": "મંડી પ્લેટફોર્મ",
        "platformDescription": "ખેડૂતો અને વેપારીઓને જોડતું AI-સંચાલિત બહુભાષી માર્કેટપ્લેસ। 22 ભારતીય ભાષાઓમાં વેપાર કરો।",
        "login": "લોગ ઇન",
        "profile": "પ્રોફાઈલ",
        "createListing": "લિસ્ટિંગ બનાવો",
        "aiInsights": "AI આંતરદૃષ્ટિ",
        "home": "હોમ",
        "listings": "યાદીઓ",
        "dashboard": "ડેશબોર્ડ",
        "settings": "સેટિંગ્સ",
        "register": "નોંધણી કરો",
        "logout": "લોગ આઉટ",
        "success": "સફળતા",
        "error": "ભૂલ",
        "selectLanguage": "ભાષા પસંદ કરો"
      },
      "mr": {
        "appName": "मार्केटप्लेस मंडी",
        "welcome": "स्वागत",
        "loading": "लोड हो रहा है...",
        "search": "खोजें",
        "searchProducts": "उत्पाद खोजें...",
        "welcomeToMandi": "मंडी में स्वागत है",
        "indianAgriculture": "भारतीय कृषि",
        "mandiPlatform": "मंडी प्लेटफॉर्म",
        "platformDescription": "किसानों और व्यापारियों को जोड़ने वाला AI-संचालित बहुभाषी मार्केटप्लेस। 22 भारतीय भाषाओं में व्यापार करें।",
        "login": "लॉग इन",
        "profile": "प्रोफाइल",
        "createListing": "लिस्टिंग तयार करा",
        "aiInsights": "AI अंतर्दृष्टि",
        "home": "होम",
        "listings": "यादी",
        "dashboard": "डैशबोर्ड",
        "settings": "सेटिंग्स",
        "register": "नोंदणी करा",
        "logout": "लॉग आउट",
        "success": "यश",
        "error": "त्रुटी",
        "selectLanguage": "भाषा निवडा"
      },
      "kn": {
        "appName": "ಮಾರ್ಕೆಟ್‌ಪ್ಲೇಸ್ ಮಂಡಿ",
        "welcome": "ಸ್ವಾಗತ",
        "loading": "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
        "search": "ಹುಡುಕಿ",
        "searchProducts": "ಉತ್ಪನ್ನಗಳನ್ನು ಹುಡುಕಿ...",
        "welcomeToMandi": "ಮಂಡಿಗೆ ಸ್ವಾಗತ",
        "indianAgriculture": "ಭಾರತೀಯ ಕೃಷಿ",
        "mandiPlatform": "ಮಂಡಿ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್",
        "platformDescription": "ರೈತರು ಮತ್ತು ವ್ಯಾಪಾರಿಗಳನ್ನು ಸಂಪರ್ಕಿಸುವ AI-ಚಾಲಿತ ಬಹುಭಾಷಾ ಮಾರುಕಟ್ಟೆ। 22 ಭಾರತೀಯ ಭಾಷೆಗಳಲ್ಲಿ ವ್ಯಾಪಾರ ಮಾಡಿ।",
        "login": "ಲಾಗಿನ್",
        "profile": "ಪ್ರೊಫೈಲ್",
        "createListing": "ಪಟ್ಟಿ ರಚಿಸಿ",
        "aiInsights": "AI ಒಳನೋಟಗಳು",
        "home": "ಮುಖಪುಟ",
        "listings": "ಪಟ್ಟಿಗಳು",
        "dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        "register": "ನೋಂದಣಿ ಮಾಡಿ",
        "logout": "ಲಾಗ್ ಔಟ್",
        "success": "ಯಶಸ್ಸು",
        "error": "ದೋಷ",
        "selectLanguage": "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ"
      },
      "ml": {
        "appName": "മാർക്കറ്റ്പ്ലേസ് മണ്ടി",
        "welcome": "സ്വാഗതം",
        "loading": "ലോഡ് ചെയ്യുന്നു...",
        "search": "തിരയുക",
        "searchProducts": "ഉൽപ്പന്നങ്ങൾ തിരയുക...",
        "welcomeToMandi": "മണ്ടിയിലേക്ക് സ്വാഗതം",
        "indianAgriculture": "ഇന്ത്യൻ കൃഷി",
        "mandiPlatform": "മണ്ടി പ്ലാറ്റ്ഫോം",
        "platformDescription": "കർഷകരെയും വ്യാപാരികളെയും ബന്ധിപ്പിക്കുന്ന AI-പവർഡ് ബഹുഭാഷാ മാർക്കറ്റ്പ്ലേസ്। 22 ഇന്ത്യൻ ഭാഷകളിൽ വ്യാപാരം നടത്തുക।",
        "login": "ലോഗിൻ",
        "profile": "പ്രൊഫൈൽ",
        "createListing": "ലിസ്റ്റിംഗ് സൃഷ്ടിക്കുക",
        "aiInsights": "AI ഇൻസൈറ്റുകൾ",
        "home": "ഹോം",
        "listings": "ലിസ്റ്റിംഗുകൾ",
        "dashboard": "ഡാഷ്ബോർഡ്",
        "settings": "സെറ്റിംഗുകൾ",
        "register": "രജിസ്റ്റർ ചെയ്യുക",
        "logout": "ലോഗ് ഔട്ട്",
        "success": "വിജയം",
        "error": "പിശക്",
        "selectLanguage": "ഭാഷ തിരഞ്ഞെടുക്കുക"
      },
      "pa": {
        "appName": "ਮਾਰਕੇਟਪਲੇਸ ਮੰਡੀ",
        "welcome": "ਸਵਾਗਤ ਹੈ",
        "loading": "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
        "search": "ਖੋਜੋ",
        "searchProducts": "ਉਤਪਾਦ ਖੋਜੋ...",
        "welcomeToMandi": "ਮੰਡੀ ਵਿੱਚ ਸਵਾਗਤ ਹੈ",
        "indianAgriculture": "ਭਾਰਤੀ ਖੇਤੀਬਾੜੀ",
        "mandiPlatform": "ਮੰਡੀ ਪਲੇਟਫਾਰਮ",
        "platformDescription": "ਕਿਸਾਨਾਂ ਅਤੇ ਵਪਾਰੀਆਂ ਨੂੰ ਜੋੜਨ ਵਾਲਾ AI-ਸੰਚਾਲਿਤ ਬਹੁਭਾਸ਼ੀ ਮਾਰਕੇਟਪਲੇਸ। 22 ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਵਪਾਰ ਕਰੋ।",
        "login": "ਲਾਗ ਇਨ",
        "profile": "ਪ੍ਰੋਫਾਈਲ",
        "createListing": "ਲਿਸਟਿੰਗ ਬਣਾਓ",
        "aiInsights": "AI ਸੂਝ",
        "home": "ਘਰ",
        "listings": "ਸੂਚੀਆਂ",
        "dashboard": "ਡੈਸ਼ਬੋਰਡ",
        "settings": "ਸੈਟਿੰਗਾਂ",
        "register": "ਰਜਿਸਟਰ ਕਰੋ",
        "logout": "ਲਾਗ ਆਉਟ",
        "success": "ਸਫਲਤਾ",
        "error": "ਗਲਤੀ",
        "selectLanguage": "ਭਾਸ਼ਾ ਚੁਣੋ"
      },
      "ur": {
        "appName": "مارکیٹ پلیس منڈی",
        "welcome": "خوش آمدید",
        "loading": "لوڈ ہو رہا ہے...",
        "search": "تلاش کریں",
        "searchProducts": "مصنوعات تلاش کریں...",
        "welcomeToMandi": "منڈی میں خوش آمدید",
        "indianAgriculture": "ہندوستانی زراعت",
        "mandiPlatform": "منڈی پلیٹ فارم",
        "platformDescription": "کسانوں اور تاجروں کو جوڑنے والا AI سے چلنے والا کثیر لسانی مارکیٹ پلیس۔ 22 ہندوستانی زبانوں میں تجارت کریں۔",
        "login": "لاگ ان",
        "profile": "پروفائل",
        "createListing": "فہرست بنائیں",
        "aiInsights": "AI بصیرت",
        "home": "ہوم",
        "listings": "فہرستیں",
        "dashboard": "ڈیش بورڈ",
        "settings": "ترتیبات",
        "register": "رجسٹر کریں",
        "logout": "لاگ آؤٹ",
        "success": "کامیابی",
        "error": "خرابی",
        "selectLanguage": "زبان منتخب کریں"
      }
    }
  },
  "localIds": [
    "common::local::src\\content\\common.content.ts"
  ]
} as const;
