/* eslint-disable */
export default {
  "key": "listings",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "createListing": "Create New Listing",
        "productName": "Product Name",
        "enterProductName": "Enter product name",
        "category": "Category",
        "selectCategory": "Select a category",
        "description": "Description",
        "enterDescription": "Enter product description",
        "quantity": "Quantity",
        "unit": "Unit",
        "askingPrice": "Asking Price",
        "priceUnit": "Price Unit",
        "state": "State",
        "district": "District",
        "pincode": "Pincode",
        "cancel": "Cancel",
        "creating": "Creating...",
        "kg": "Kg",
        "gram": "Gram",
        "ton": "Ton",
        "piece": "Piece",
        "dozen": "Dozen",
        "liter": "Liter",
        "perKg": "Per Kg",
        "perGram": "Per Gram",
        "perTon": "Per Ton",
        "perPiece": "Per Piece",
        "perDozen": "Per Dozen",
        "perLiter": "Per Liter"
      },
      "hi": {
        "createListing": "नई लिस्टिंग बनाएं",
        "productName": "उत्पाद का नाम",
        "enterProductName": "उत्पाद का नाम दर्ज करें",
        "category": "श्रेणी",
        "selectCategory": "एक श्रेणी चुनें",
        "description": "विवरण",
        "enterDescription": "उत्पाद विवरण दर्ज करें",
        "quantity": "मात्रा",
        "unit": "इकाई",
        "askingPrice": "मांगी गई कीमत",
        "priceUnit": "मूल्य इकाई",
        "state": "राज्य",
        "district": "जिला",
        "pincode": "पिनकोड",
        "cancel": "रद्द करें",
        "creating": "बनाया जा रहा है...",
        "kg": "किलो",
        "gram": "ग्राम",
        "ton": "टन",
        "piece": "टुकड़ा",
        "dozen": "दर्जन",
        "liter": "लीटर",
        "perKg": "प्रति किलो",
        "perGram": "प्रति ग्राम",
        "perTon": "प्रति टन",
        "perPiece": "प्रति टुकड़ा",
        "perDozen": "प्रति दर्जन",
        "perLiter": "प्रति लीटर"
      },
      "bn": {
        "createListing": "নতুন তালিকা তৈরি করুন",
        "productName": "পণ্যের নাম",
        "enterProductName": "পণ্যের নাম লিখুন",
        "category": "বিভাग",
        "selectCategory": "একটি বিভাগ নির্বাচন করুন",
        "description": "বিবরণ",
        "enterDescription": "পণ্যের বিবরণ লিখুন",
        "quantity": "পরিমাণ",
        "unit": "একক",
        "askingPrice": "চাহিদা মূল্য",
        "priceUnit": "মূল্য একক",
        "state": "রাজ্য",
        "district": "জেলা",
        "pincode": "পিনকোড",
        "cancel": "বাতিল",
        "creating": "তৈরি করা হচ্ছে...",
        "kg": "কেজি",
        "gram": "গ্রাম",
        "ton": "টন",
        "piece": "টুকরা",
        "dozen": "ডজন",
        "liter": "লিটার",
        "perKg": "প্রতি কেজি",
        "perGram": "প্রতি গ্রাম",
        "perTon": "প্রতি টন",
        "perPiece": "প্রতি টুকরা",
        "perDozen": "প্রতি ডজন",
        "perLiter": "প্রতি লিটার"
      },
      "ta": {
        "createListing": "புதிய பட்டியல் உருவாக்கவும்",
        "productName": "தயாரிப்பு பெயர்",
        "enterProductName": "தயாரிப்பு பெயரை உள்ளிடவும்",
        "category": "வகை",
        "selectCategory": "ஒரு வகையைத் தேர்ந்தெடுக்கவும்",
        "description": "விளக்கம்",
        "enterDescription": "தயாரிப்பு விளக்கத்தை உள்ளிடவும்",
        "quantity": "அளவு",
        "unit": "அலகு",
        "askingPrice": "கேட்கும் விலை",
        "priceUnit": "விலை அலகு",
        "state": "மாநிலம்",
        "district": "மாவட்டம்",
        "pincode": "பின்கோட்",
        "cancel": "ரத்து செய்",
        "creating": "உருவாக்கப்படுகிறது...",
        "kg": "கிலோ",
        "gram": "கிராம்",
        "ton": "டன்",
        "piece": "துண்டு",
        "dozen": "டஜன்",
        "liter": "லிட்டர்",
        "perKg": "ஒரு கிலோவுக்கு",
        "perGram": "ஒரு கிராமுக்கு",
        "perTon": "ஒரு டன்னுக்கு",
        "perPiece": "ஒரு துண்டுக்கு",
        "perDozen": "ஒரு டஜனுக்கு",
        "perLiter": "ஒரு லிட்டருக்கு"
      },
      "te": {
        "createListing": "కొత్త జాబితా సృష్టించండి",
        "productName": "ఉత్పత్తి పేరు",
        "enterProductName": "ఉత్పత్తి పేరు నమోదు చేయండి",
        "category": "వర్గం",
        "selectCategory": "ఒక వర్గాన్ని ఎంచుకోండి",
        "description": "వివరణ",
        "enterDescription": "ఉత్పత్తి వివరణను నమోదు చేయండి",
        "quantity": "పరిమాణం",
        "unit": "యూనిట్",
        "askingPrice": "అడుగుతున్న ధర",
        "priceUnit": "ధర యూనిట్",
        "state": "రాష్ట్రం",
        "district": "జిల్లా",
        "pincode": "పిన్‌కోడ్",
        "cancel": "రద్దు చేయండి",
        "creating": "సృష్టిస్తోంది...",
        "kg": "కిలో",
        "gram": "గ్రాము",
        "ton": "టన్",
        "piece": "ముక్క",
        "dozen": "డజను",
        "liter": "లీటర్",
        "perKg": "కిలోకు",
        "perGram": "గ్రాముకు",
        "perTon": "టన్నుకు",
        "perPiece": "ముక్కకు",
        "perDozen": "డజనుకు",
        "perLiter": "లీటరుకు"
      },
      "gu": {
        "createListing": "નવી યાદી બનાવો",
        "productName": "ઉત્પાદનનું નામ",
        "enterProductName": "ઉત્પાદનનું નામ દાખલ કરો",
        "category": "શ્રેણી",
        "selectCategory": "એક શ્રેણી પસંદ કરો",
        "description": "વર્ણન",
        "enterDescription": "ઉત્પાદન વર્ણન દાખલ કરો",
        "quantity": "માત્રા",
        "unit": "એકમ",
        "askingPrice": "માંગેલ કિંમત",
        "priceUnit": "કિંમત એકમ",
        "state": "રાજ્ય",
        "district": "જિલ્લો",
        "pincode": "પિનકોડ",
        "cancel": "રદ કરો",
        "creating": "બનાવવામાં આવી રહ્યું છે...",
        "kg": "કિલો",
        "gram": "ગ્રામ",
        "ton": "ટન",
        "piece": "ટુકડો",
        "dozen": "ડઝન",
        "liter": "લિટર",
        "perKg": "પ્રતિ કિલો",
        "perGram": "પ્રતિ ગ્રામ",
        "perTon": "પ્રતિ ટન",
        "perPiece": "પ્રતિ ટુકડો",
        "perDozen": "પ્રતિ ડઝન",
        "perLiter": "પ્રતિ લિટર"
      },
      "mr": {
        "createListing": "नवीन यादी तयार करा",
        "productName": "उत्पादनाचे नाव",
        "enterProductName": "उत्पादनाचे नाव प्रविष्ट करा",
        "category": "श्रेणी",
        "selectCategory": "एक श्रेणी निवडा",
        "description": "वर्णन",
        "enterDescription": "उत्पादन वर्णन प्रविष्ट करा",
        "quantity": "प्रमाण",
        "unit": "एकक",
        "askingPrice": "मागणी किंमत",
        "priceUnit": "किंमत एकक",
        "state": "राज्य",
        "district": "जिल्हा",
        "pincode": "पिनकोड",
        "cancel": "रद्द करा",
        "creating": "तयार केले जात आहे...",
        "kg": "किलो",
        "gram": "ग्राम",
        "ton": "टन",
        "piece": "तुकडा",
        "dozen": "डझन",
        "liter": "लिटर",
        "perKg": "प्रति किलो",
        "perGram": "प्रति ग्राम",
        "perTon": "प्रति टन",
        "perPiece": "प्रति तुकडा",
        "perDozen": "प्रति डझन",
        "perLiter": "प्रति लिटर"
      },
      "kn": {
        "createListing": "ಹೊಸ ಪಟ್ಟಿ ರಚಿಸಿ",
        "productName": "ಉತ್ಪನ್ನದ ಹೆಸರು",
        "enterProductName": "ಉತ್ಪನ್ನದ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
        "category": "ವರ್ಗ",
        "selectCategory": "ಒಂದು ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
        "description": "ವಿವರಣೆ",
        "enterDescription": "ಉತ್ಪನ್ನದ ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ",
        "quantity": "ಪ್ರಮಾಣ",
        "unit": "ಘಟಕ",
        "askingPrice": "ಕೇಳುವ ಬೆಲೆ",
        "priceUnit": "ಬೆಲೆ ಘಟಕ",
        "state": "ರಾಜ್ಯ",
        "district": "ಜಿಲ್ಲೆ",
        "pincode": "ಪಿನ್‌ಕೋಡ್",
        "cancel": "ರದ್ದುಮಾಡಿ",
        "creating": "ರಚಿಸಲಾಗುತ್ತಿದೆ...",
        "kg": "ಕಿಲೋ",
        "gram": "ಗ್ರಾಂ",
        "ton": "ಟನ್",
        "piece": "ತುಂಡು",
        "dozen": "ಡಜನ್",
        "liter": "ಲೀಟರ್",
        "perKg": "ಪ್ರತಿ ಕಿಲೋ",
        "perGram": "ಪ್ರತಿ ಗ್ರಾಂ",
        "perTon": "ಪ್ರತಿ ಟನ್",
        "perPiece": "ಪ್ರತಿ ತುಂಡು",
        "perDozen": "ಪ್ರತಿ ಡಜನ್",
        "perLiter": "ಪ್ರತಿ ಲೀಟರ್"
      },
      "ml": {
        "createListing": "പുതിയ ലിസ്റ്റിംഗ് സൃഷ്ടിക്കുക",
        "productName": "ഉൽപ്പന്നത്തിന്റെ പേര്",
        "enterProductName": "ഉൽപ്പന്നത്തിന്റെ പേര് നൽകുക",
        "category": "വിഭാഗം",
        "selectCategory": "ഒരു വിഭാഗം തിരഞ്ഞെടുക്കുക",
        "description": "വിവരണം",
        "enterDescription": "ഉൽപ്പന്ന വിവരണം നൽകുക",
        "quantity": "അളവ്",
        "unit": "യൂണിറ്റ്",
        "askingPrice": "ചോദിക്കുന്ന വില",
        "priceUnit": "വില യൂണിറ്റ്",
        "state": "സംസ്ഥാനം",
        "district": "ജില്ല",
        "pincode": "പിൻകോഡ്",
        "cancel": "റദ്ദാക്കുക",
        "creating": "സൃഷ്ടിക്കുന്നു...",
        "kg": "കിലോ",
        "gram": "ഗ്രാം",
        "ton": "ടൺ",
        "piece": "കഷണം",
        "dozen": "ഡസൻ",
        "liter": "ലിറ്റർ",
        "perKg": "ഒരു കിലോയ്ക്ക്",
        "perGram": "ഒരു ഗ്രാമിന്",
        "perTon": "ഒരു ടണ്ണിന്",
        "perPiece": "ഒരു കഷണത്തിന്",
        "perDozen": "ഒരു ഡസനു",
        "perLiter": "ഒരു ലിറ്ററിന്"
      },
      "pa": {
        "createListing": "ਨਵੀਂ ਲਿਸਟਿੰਗ ਬਣਾਓ",
        "productName": "ਉਤਪਾਦ ਦਾ ਨਾਮ",
        "enterProductName": "ਉਤਪਾਦ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ",
        "category": "ਸ਼੍ਰੇਣੀ",
        "selectCategory": "ਇੱਕ ਸ਼੍ਰੇਣੀ ਚੁਣੋ",
        "description": "ਵਰਣਨ",
        "enterDescription": "ਉਤਪਾਦ ਦਾ ਵਰਣਨ ਦਰਜ ਕਰੋ",
        "quantity": "ਮਾਤਰਾ",
        "unit": "ਇਕਾਈ",
        "askingPrice": "ਮੰਗੀ ਗਈ ਕੀਮਤ",
        "priceUnit": "ਕੀਮਤ ਇਕਾਈ",
        "state": "ਰਾਜ",
        "district": "ਜ਼ਿਲ੍ਹਾ",
        "pincode": "ਪਿੰਨਕੋਡ",
        "cancel": "ਰੱਦ ਕਰੋ",
        "creating": "ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...",
        "kg": "ਕਿਲੋ",
        "gram": "ਗ੍ਰਾਮ",
        "ton": "ਟਨ",
        "piece": "ਟੁਕੜਾ",
        "dozen": "ਦਰਜਨ",
        "liter": "ਲੀਟਰ",
        "perKg": "ਪ੍ਰਤੀ ਕਿਲੋ",
        "perGram": "ਪ੍ਰਤੀ ਗ੍ਰਾਮ",
        "perTon": "ਪ੍ਰਤੀ ਟਨ",
        "perPiece": "ਪ੍ਰਤੀ ਟੁਕੜਾ",
        "perDozen": "ਪ੍ਰਤੀ ਦਰਜਨ",
        "perLiter": "ਪ੍ਰਤੀ ਲੀਟਰ"
      },
      "ur": {
        "createListing": "نئی فہرست بنائیں",
        "productName": "پروڈکٹ کا نام",
        "enterProductName": "پروڈکٹ کا نام درج کریں",
        "category": "قسم",
        "selectCategory": "ایک قسم منتخب کریں",
        "description": "تفصیل",
        "enterDescription": "پروڈکٹ کی تفصیل درج کریں",
        "quantity": "مقدار",
        "unit": "یونٹ",
        "askingPrice": "مانگی گئی قیمت",
        "priceUnit": "قیمت یونٹ",
        "state": "ریاست",
        "district": "ضلع",
        "pincode": "پن کوڈ",
        "cancel": "منسوخ کریں",
        "creating": "بنایا جا رہا ہے...",
        "kg": "کلو",
        "gram": "گرام",
        "ton": "ٹن",
        "piece": "ٹکڑا",
        "dozen": "درجن",
        "liter": "لیٹر",
        "perKg": "فی کلو",
        "perGram": "فی گرام",
        "perTon": "فی ٹن",
        "perPiece": "فی ٹکڑا",
        "perDozen": "فی درجن",
        "perLiter": "فی لیٹر"
      }
    }
  },
  "localIds": [
    "listings::local::src\\content\\listings.content.ts"
  ]
} as const;
